version: '2'

services:

  jupyter:
    image: jayjohnson/jupyter:2.0.2
    container_name: "jupyter"
    hostname: "jupyter"
    env_file: 
      - ./justredis/redis-labs.env
    ports:
      - "82:8888"
    volumes:
      - /opt/project:/opt/project
      - /opt/work:/opt/work
      - ./configs:/opt/work/configs
      - ./examples:/opt/work/examples
    network_mode: "host"

